drop table if exists book;
drop table if exists person;
create table person(
                       id int generated by default as identity primary key,
                       name varchar unique not null,
                       year int check ( year>0) NOT NULL
);



create table book(
                     id int generated by default as identity primary key,
                     name varchar NOT NULL,
                     author varchar NOT NULL,
                     year int check ( year>0) NOT NULL,
                     person_id int  REFERENCES person(id) ON DELETE SET NULL
);






-- drop table book